<a href="https://colab.research.google.com/github/Maheshcheegiti/FML/blob/main/numpynotes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
#importing numpy
import numpy as np
#checking version
np.__version__

'1.22.4'

In [3]:
#creating array
arr = np.array(10)
print(arr)
print(type(arr))
arr = np.array((1,2,3,4,5))
print(arr)

10
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
#0 dimensional arrays
arr = np.array(40)
print(arr.shape)
print(arr.ndim)
print(arr)

()
0
40


In [5]:
#1 dimensional arrays
arr = np.array([1,2,3,4,5])
print(arr.shape)
print(arr.ndim)
print(arr)

(5,)
1
[1 2 3 4 5]


In [6]:
#2-d arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr)

(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [7]:
#3-d arrays
arr = np.array([[[1,2,3],[3,4,5]],
                [[7,8,9],[4,5,6]]])
print(arr.shape)
print(arr.ndim)
print(arr)

(2, 2, 3)
3
[[[1 2 3]
  [3 4 5]]

 [[7 8 9]
  [4 5 6]]]


In [8]:
#creating dimensional arrays
arr = np.array([1,2,3,4],ndmin=5)
print(arr.ndim)
print(arr.shape)
print(arr)

5
(1, 1, 1, 1, 4)
[[[[[1 2 3 4]]]]]


In [9]:
#array indexing 
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1]+arr[3])

1
6


In [10]:
#accessing 2-d arrays
arr = np.array([[1,2,3,4],[1,2,3,4]])
print(arr[0,1])  #for 3-d arr[i,j,k]
#negitive indexing
print(arr[0,-1])

2
4


In [11]:
#slicing
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:4])
print(arr[1:10:2]) #start end step
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1:2])
print(arr[1:2,1:2]) # u can use step also

[2 3 4]
[ 2  4  6  8 10]
[[4 5 6]]
[[5]]


In [12]:
#data types
arr = np.array([1,2,3,4])
print(arr.dtype)
arr = np.array([1,2,3,4],dtype='S')
print(arr.dtype)

int64
|S1


In [13]:
#copy and view
arr = np.array([1,2,3,4])
x = arr.copy()
y = arr.view()
print(x)
arr[0] = 4
print(arr)
print(x) #not changed
print(y) #changed

[1 2 3 4]
[4 2 3 4]
[1 2 3 4]
[4 2 3 4]


In [14]:
#re-shape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
#iterating
arr = np.array([1,2,3,4,5,6])
for i in arr:
  print(i)

1
2
3
4
5
6


In [16]:
#concatenation
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,8,9,10])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[ 1  2  3  4  5  6  4  5  6  8  9 10]


In [17]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [18]:
#split
arr = np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [19]:
#search
print(np.where(arr == 4))

(array([3]),)


In [20]:
#sort
print(np.sort(arr))

[1 2 3 4 5 6]


In [21]:
#filter
filter_arr = arr>3
print(filter_arr)

[False False False  True  True  True]


In [22]:
#add subtract multiply and sum
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,5],[7,6]])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.sum((arr1,arr2),axis=1))

[[ 5  7]
 [10 10]]
[[-3 -3]
 [-4 -2]]
[[ 4 10]
 [21 24]]
[[ 4  6]
 [11 11]]


In [23]:
#transpose
print(arr.T)

[1 2 3 4 5 6]
